### ISSUE TITLE
hi, application Please help setup

### ISSUE THREAD

**Issue by byzatwuer** [prathmeshranaut/skooterapi#1]
I downloaded the application and tried to install it
But how do I install ruby ​​api
Please help me.
You will help me when we build the application.

Can you explain the setup step by step please

**Comment by prathmeshranaut** [comment]
Sorry for having no documentation for the API, I'll write a documentation to install the ruby backend this weekend.

**Comment by byzatwuer** [comment]
Ok thanks. Do not write database links ?

**Comment by byzatwuer** [comment]
I'm curiously waiting, Would you elaborate plase.

Can you write it as php?

**Comment by prathmeshranaut** [comment]
I've written the docs to install the server. https://github.com/prathmeshranaut/skooterapi/blob/master/README.md

**Comment by byzatwuer** [comment]
How can I provide access to the admin folder

Thanks bro.
