### ISSUE TITLE
Please help me get the error.

### ISSUE THREAD

**Issue by byzatwuer** [prathmeshranaut/skooterapi#5]
@prathmeshranaut   

Please help me get the error.

`=> Booting WEBrick
=> Rails 4.2.5 application starting in development on http://5.39.5.63:8080
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2017-04-05 06:53:06] INFO  WEBrick 1.3.1
[2017-04-05 06:53:06] INFO  ruby 2.3.1 (2016-04-26) [x86_64-linux]
[2017-04-05 06:53:06] INFO  WEBrick::HTTPServer#start: pid=10371 port=8080

Started GET "/admins/sign_in" for 88.234.57.48 at 2017-04-05 06:53:12 -0400
Cannot render console from 88.234.57.48! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
  ActiveRecord::SchemaMigration Load (0.2ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by Devise::SessionsController#new as HTML
  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/devise-4.2.1/app/views/devise/shared/_links.html.erb (4.0ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/devise-4.2.1/app/views/devise/sessions/new.html.erb within layouts/application (35.6ms)
Completed 200 OK in 184ms (Views: 164.4ms | ActiveRecord: 1.4ms)

Started GET "/assets/analytics.self-877aef30ae1b040ab8a3aba4e3e309a11d7f2612f44dde450b5c157aa5f95c05.js?body=1" for 88.234.57.48 at 2017-04-05 06:53:12 -0400
Cannot render console from 88.234.57.48! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255

Started GET "/assets/content.self-877aef30ae1b040ab8a3aba4e3e309a11d7f2612f44dde450b5c157aa5f95c05.js?body=1" for 88.234.57.48 at 2017-04-05 06:53:12 -0400
Cannot render console from 88.234.57.48! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255

Started GET "/assets/moderator.self-877aef30ae1b040ab8a3aba4e3e309a11d7f2612f44dde450b5c157aa5f95c05.js?body=1" for 88.234.57.48 at 2017-04-05 06:53:12 -0400
Cannot render console from 88.234.57.48! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255

Started GET "/assets/application.self-3a3c8b61bda630ee689740ce7cbd0dd8ea6fdd45e2c42eef4661ab38cf268afe.js?body=1" for 88.234.57.48 at 2017-04-05 06:53:12 -0400
Cannot render console from 88.234.57.48! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255

Started POST "/user" for 88.234.57.48 at 2017-04-05 06:53:21 -0400
Cannot render console from 88.234.57.48! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255

ActionController::RoutingError (No route matches [POST] "/user"):
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:20:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  rack (1.6.5) lib/rack/lock.rb:17:in `call'
  rack (1.6.5) lib/rack/content_length.rb:15:in `call'
  rack (1.6.5) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (0.7ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/routes/_route.html.erb (1.5ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/routes/_table.html.erb (1.2ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (19.1ms)
`

**Comment by byzatwuer** [comment]
Started POST "/user" for 88.234.57.48 at 2017-04-05 07:42:49 -0400

ActionController::RoutingError (No route matches [POST] "/user"):
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:20:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  rack (1.6.5) lib/rack/lock.rb:17:in `call'
  rack (1.6.5) lib/rack/content_length.rb:15:in `call'
  rack (1.6.5) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (0.7ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/routes/_route.html.erb (1.5ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/routes/_table.html.erb (0.7ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.6ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (17.1ms)

**Comment by byzatwuer** [comment]
Why did he give such an error?

**Comment by byzatwuer** [comment]
@prathmeshranaut

**Comment by byzatwuer** [comment]
ActionController::RoutingError (No route matches [POST] "/user"):

**Comment by prathmeshranaut** [comment]
You should call something like : http://5.39.5.63:8080/api/v1/user

**Comment by byzatwuer** [comment]
Thanks but where do i write it

what should I do
I do not understand ruby

**Comment by byzatwuer** [comment]
skooter app main url ?

**Comment by byzatwuer** [comment]
Started POST "/user" for 88.234.57.48 at 2017-04-05 08:00:01 -0400

ActionController::RoutingError (No route matches [POST] "/user"):
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:20:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  rack (1.6.5) lib/rack/lock.rb:17:in `call'
  rack (1.6.5) lib/rack/content_length.rb:15:in `call'
  rack (1.6.5) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (0.7ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/routes/_route.html.erb (1.4ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/routes/_table.html.erb (0.7ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.7ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (17.0ms)




I am getting such an error

**Comment by byzatwuer** [comment]
class Application < Rails::Application
  config.web_console.whiny_requests = false
end

config/development.rb I added

**Comment by byzatwuer** [comment]
I am getting the error I wrote above

When I try to test it from my phone it stays on the login screen again
And it always returns the code refresh I wrote above

**Comment by byzatwuer** [comment]
What should I do

**Comment by byzatwuer** [comment]
@prathmeshranaut  routes.rb In the file  post 'api/:version/user' => 'user#create_user' 

http://5.39.5.63:8080/api/v1/user

Will it be that way ?

@prathmeshranaut 
There is still the same error

**Comment by byzatwuer** [comment]
Please help me.

**Comment by prathmeshranaut** [comment]
Did you change the API URL in the app?

**Comment by byzatwuer** [comment]
@prathmeshranaut 

skooterapp api.xml I changed the main url in

Is there something else I should do

**Comment by byzatwuer** [comment]
Started POST "/user" for 88.234.57.48 at 2017-04-05 10:46:57 -0400
  ActiveRecord::SchemaMigration Load (0.3ms)  SELECT "schema_migrations".* FROM "schema_migrations"

**Comment by prathmeshranaut** [comment]
This seems to be correct.

**Comment by byzatwuer** [comment]
But I'm getting an error. Application not working. Loading screen does not pass

**Comment by byzatwuer** [comment]
@prathmeshranaut

**Comment by byzatwuer** [comment]
Hep me please

**Comment by prathmeshranaut** [comment]
Your server refused to connect.

**Comment by byzatwuer** [comment]
I m  give you server information you. Would you set up a api for me? Please 
My head stopped.

@prathmeshranaut

**Comment by byzatwuer** [comment]
http://5.39.5.63:8080/admins/sign_in 

active

**Comment by byzatwuer** [comment]
Started POST "/api/v1/user" for 103.211.52.130 at 2017-04-05 13:53:53 -0400
Processing by UserController#create_user as */*
  Parameters: {"visitor_id"=>"1", "token"=>"29786449586dc5557a7028162ac794e93651efa1", "limit"=>"10", "page"=>"1", "conversation_id"=>"13", "recipients"=>"testuser", "title"=>"New Conversation", "message"=>"Message"}
Can't verify CSRF token authenticity
Unpermitted parameters: visitor_id, token, limit, page, conversation_id, recipients, title, message
  User Load (0.9ms)  SELECT  "users".* FROM "users" LIMIT 1
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
   (0.0ms)  BEGIN
   (0.0ms)  ROLLBACK
Completed 501 Not Implemented in 30ms (Views: 0.1ms | ActiveRecord: 1.7ms)

**Comment by byzatwuer** [comment]
Started GET "/api/v1/skoot/1/1" for 103.211.52.130 at 2017-04-05 13:55:24 -0400
  ActiveRecord::SchemaMigration Load (0.2ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by SkootController#show_skoot as HTML
  Parameters: {"skoot_id"=>"1", "location_id"=>"1"}
Filter chain halted as :restrict_access rendered or redirected
Completed 401 Unauthorized in 6ms (Views: 0.1ms | ActiveRecord: 0.0ms)

**Comment by prathmeshranaut** [comment]
That was me trying to send a request. In your app, try creating a user now or change the API URL to : http://5.39.5.63:8080/api/v1/

**Comment by byzatwuer** [comment]
skooterapp api.xml files in code main url ?

**Comment by prathmeshranaut** [comment]
Yes

**Comment by byzatwuer** [comment]
same again. The loading screen remains


I m give you server information you. Would you set up a api for me? Please
My head stopped.


server ip: 5.39.5.63
server username: root
server password: edirnekesan

Log into the server and check please
I'm doing the right thing ?

**Comment by byzatwuer** [comment]
@prathmeshranaut

**Comment by prathmeshranaut** [comment]
I might be able to look into it this weekend if I get the time.

**Comment by byzatwuer** [comment]
@prathmeshranaut server Save info. I will remove server information from here

**Comment by byzatwuer** [comment]
Please eye to the server for the weekend 

@prathmeshranaut

I am waiting
