### ISSUE TITLE
skooterapi: I can not bypass the opening screen. That's what happens with skooterapi.  Why can not I open the opening screen pass.

### ISSUE THREAD

**Issue by byzatwuer** [prathmeshranaut/skooterapi#6]
hello @prathmeshranaut 

**I can not bypass the opening screen. That's what happens with skooterapi.  Why can not I open the opening screen pass.**

I will go nuts please help me @prathmeshranaut  please.

```
Started POST "/api/v1/user" for 176.54.70.157 at 2017-04-08 11:27:42 -0400
Cannot render console from 176.54.70.157! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by UserController#create_user as HTML
  Parameters: {"phone"=>"1234456677654", "android_version"=>"22", "device_info"=>"htc HTC Desire 830", "version"=>"v1", "user"=>{}}
Can't verify CSRF token authenticity
Unpermitted parameters: phone, android_version, device_info, version, user
  User Load (0.2ms)  SELECT  "users".* FROM "users" LIMIT 1
   (0.0ms)  BEGIN
   (0.1ms)  ROLLBACK
   (0.0ms)  BEGIN
   (0.0ms)  ROLLBACK
Completed 501 Not Implemented in 3ms (Views: 0.1ms | ActiveRecord: 0.4ms)
```

**Comment by byzatwuer** [comment]
**config aplications.rb  I added this code**   @prathmeshranaut 

```
### 	 require 'socket'
require 'ipaddr'
  config.web_console.whitelisted_ips = Socket.ip_address_list.reduce([]) do |res, addrinfo|
    addrinfo.ipv4? ? res << IPAddr.new(addrinfo.ip_address).mask(24) : res
end

```


**error It changed in this way**

```
### Started POST "/api/v1/user" for 176.55.165.228 at 2017-04-08 11:56:19 -0400
  ActiveRecord::SchemaMigration Load (0.2ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by UserController#create_user as HTML
  Parameters: {"phone"=>"2bfcc3088526737b", "android_version"=>"22", "device_info"=>"htc HTC Desire 830", "version"=>"v1", "user"=>{}}
Can't verify CSRF token authenticity
Unpermitted parameters: phone, android_version, device_info, version, user
  User Load (0.3ms)  SELECT  "users".* FROM "users" LIMIT 1
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
   (0.0ms)  BEGIN
   (0.1ms)  ROLLBACK
Completed 501 Not Imp
```

**Comment by prathmeshranaut** [comment]
`Can't verify CSRF token authenticity`
This is the issue. 

Check this out : http://stackoverflow.com/questions/27393694/ruby-on-rails-json-rest-api-csrf-token

**Comment by byzatwuer** [comment]
I did not understand. What am I going to do now I am new to ruby @prathmeshranaut

**Comment by byzatwuer** [comment]
please help me. @prathmeshranaut

**Comment by prathmeshranaut** [comment]
Add this line
`skip_before_filter  :verify_authenticity_token`
here
https://github.com/prathmeshranaut/skooterapi/blob/master/app/controllers/user_controller.rb#L5

**Comment by byzatwuer** [comment]
```
Started POST "/api/v1/user" for 176.54.87.35 at 2017-04-09 02:40:54 -0400
Processing by UserController#create_user as HTML
  Parameters: {"phone"=>"2bfcc3088526737b", "android_version"=>"22", "device_info"=>"htc HTC Desire 830", "user"=>{}}
Unpermitted parameters: phone, android_version, device_info, user
  User Load (0.2ms)  SELECT  "users".* FROM "users" LIMIT 1
   (0.0ms)  BEGIN
   (0.0ms)  ROLLBACK
   (0.0ms)  BEGIN
   (0.0ms)  ROLLBACK
Completed 501 Not Implemented in 3ms (Views: 0.1ms | ActiveRecord: 0.3ms)

```




@prathmeshranaut I cannot cross the login screen again.

**Comment by byzatwuer** [comment]
Could you check my server. @prathmeshranaut 

Login information
5.39.5.63
login username: root
password: Siber999

postgresql password: edirnekesan1996

**Comment by prathmeshranaut** [comment]
Could you tell me where have you stored this API and how do you turn on the rails server?

**Comment by byzatwuer** [comment]
@prathmeshranaut  

root folder in skooterapi file

Via ubuntu, I installed ruby ​​on rails directly and imported the skooterapi file to the server with git clone.
 PostgreSQL and phppgadmin installations Then I did the readme.md file on your process. And I ran the rails.

Ruby on rails new there is something else i need to do ?

**Comment by byzatwuer** [comment]
Are you going to help ? @prathmeshranaut

**Comment by prathmeshranaut** [comment]
I am actually looking into the server and code.

**Comment by byzatwuer** [comment]
I was doing some processing on the server. I left the server to you
@prathmeshranaut

**Comment by prathmeshranaut** [comment]
The libraries have been updated since we coded this API. I would suggest you to use the code as a starter for creating your own API.

PS: Please change the password of your server.

**Comment by byzatwuer** [comment]
Ruby on railste I do not know what to do next I can not use this skooterapi I guess. @prathmeshranaut

**Comment by byzatwuer** [comment]
Ruby on railste new
@prathmeshranaut

**Comment by prathmeshranaut** [comment]
You cant

**Comment by byzatwuer** [comment]
I did not understand
@prathmeshranaut

**Comment by prathmeshranaut** [comment]
You can use this code to build an API in a language you understand.

**Comment by byzatwuer** [comment]
It is not api anyway ?
 @prathmeshranaut

**Comment by prathmeshranaut** [comment]
No, it's broken now.

**Comment by byzatwuer** [comment]
I will write the api with php. Do I need to change the content of the SkooterApp? @prathmeshranaut 
Or do you need to compile the json codes that ı m wrote in php?

**Comment by byzatwuer** [comment]
I will write the api with php. Do I need to change the content of the SkooterApp? @prathmeshranaut
Or do you need to compile the json codes that ı m wrote in php? @prathmeshranaut

**Comment by prathmeshranaut** [comment]
No, SkooterApp is modular, just modify the API URL. That would be it.
